class TipoToken:
    """
    Esta classe guarda quais são os tipos de tokens possíveis
    """
    ID = (1, 'id')
    CTE = (2, 'cte')  # numero
    CADEIA = (3, 'cadeia')
    PROGRAMA = (4, 'programa')
    VARIAVEIS = (5, 'variaveis')
    INTEIRO = (6, 'inteiro')
    REAL = (7, 'real')
    LOGICO = (8, 'logico')
    CARACTER = (9, 'caracter')
    SE = (10, 'se')
    SENAO = (11, 'senao')
    ENQUANTO = (12, 'enquanto')
    LEIA = (13, 'leia')
    ESCREVA = (14, 'escreva')
    FALSO = (15, 'falso')
    VERDADEIRO = (16, 'verdadeiro')
    ATRIB = (17, ':=')
    OPREL = (18, 'operadores-relacionais')
    OPAD = (19, 'operadores-adicao')
    OPMUL = (20, 'operadores-multiplicacao')
    OPNEG = (21, '!')
    PVIRG = (22, ';')
    DPONTOS = (24, ':')
    VIRG = (25, ',')
    ABREPAR = (26, '(')
    FECHAPAR = (27, ')')
    ABRECH = (28, '{')
    FECHACH = (29, '}')
    ERROR = (31, 'erro')
    FIMARQ = (32, 'fim-de-arquivo')
